/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bmsceplacements;

import java.applet.AppletContext;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Properties;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Nilansh Thakur
 */
public class studentlist extends javax.swing.JFrame {

    /**
     * Creates new form studentlist
     */
    public studentlist() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        showdate();
        showtime();
    }
    public void showdate(){
        java.util.Date d=new java.util.Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yyyy");
        datevar.setText(s.format(d));
    }
    public void showtime(){
        new Timer(0,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                java.util.Date d=new java.util.Date();
                SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss a");
                timevar.setText(s.format(d));
            }
        }).start();    
    }
    //Function to check if entered email is valid
    public static boolean isValid(String email) 
    { 
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
                              
        Pattern pat = Pattern.compile(emailRegex); 
        if (email == null) 
            return false; 
        return pat.matcher(email).matches(); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agenda = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        emails = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        timing = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        allstudents = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        datevar = new javax.swing.JLabel();
        timevar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t01 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1500));
        setSize(new java.awt.Dimension(1500, 1500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER EMAIL ID's:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, 244, 39));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SCHEDULE MEETING:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 450, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DETAILS OF THE MEETING:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 490, 36));

        agenda.setColumns(20);
        agenda.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        agenda.setRows(5);
        jScrollPane1.setViewportView(agenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 510, -1, 150));

        emails.setColumns(20);
        emails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        emails.setRows(5);
        jScrollPane2.setViewportView(emails);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 670, -1, 150));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SETUP MEETING");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 440, 79));

        date.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 102, 102));
        date.setText("SETUP DATE(YYYY-MM-DD)");
        date.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 360, 390, 50));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 840, 160, 50));

        timing.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        timing.setForeground(new java.awt.Color(255, 102, 102));
        timing.setText("SCHEDULE TIMING(HH:MM)");
        timing.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(timing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, 390, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Set a new Meeting:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 480, 42));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SCHEDULE TIMING:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 440, 47));

        allstudents.setBackground(new java.awt.Color(0, 0, 0));
        allstudents.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        allstudents.setForeground(new java.awt.Color(255, 255, 255));
        allstudents.setText("ALL");
        allstudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allstudentsActionPerformed(evt);
            }
        });
        getContentPane().add(allstudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEND TO ALL STUDENTS:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 223, 52));

        datevar.setBackground(new java.awt.Color(0, 0, 0));
        datevar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        datevar.setForeground(new java.awt.Color(255, 255, 255));
        datevar.setText("Date:");
        getContentPane().add(datevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, 40));

        timevar.setBackground(new java.awt.Color(0, 0, 0));
        timevar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        timevar.setForeground(new java.awt.Color(255, 255, 255));
        timevar.setText("Time:");
        getContentPane().add(timevar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 220, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("OR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmslogo111.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 400, 400));

        t01.setBackground(new java.awt.Color(0, 0, 0));
        t01.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t01.setForeground(new java.awt.Color(255, 255, 255));
        t01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DATE", "TIMING", "AGENDA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(t01);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 770, 100));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Meeting History:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 480, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int error=0;
        try{
            // Input the date, time and agenda of the meeting from the form
            String date1=date.getText();
            String agenda1=agenda.getText();
            String timing1=timing.getText();
            String emails1=emails.getText();
            String[] toemail=emails1.split("\n");
            //String[] toemail1 = null;
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bmsceplacements","root","");
                int count2=0;
                int count1=0;
                if(allstudents.isSelected()){
                    count1=1;
                }else{

                for(String i: toemail){
                    boolean b=isValid(i);
                    if(b==false){
                        count2=1;
                        JOptionPane.showMessageDialog(null,"Invalid email: "+i+"");
                    }
                }
                }
                if(count2==1){
                    JOptionPane.showMessageDialog(null,"Please correct all the invalid emails");
                }
                else if(count1==1){
                    //int error=0;
                    Statement st22 =con.createStatement();
                    ResultSet rs22 =st22.executeQuery("select email from student");
                    ArrayList<String> arr=new ArrayList<String>();
                    while(rs22.next()){
                        System.out.println(0+"");
                        String email12=rs22.getString("email");
                        arr.add(email12);
                    }
                    String[] a=arr.toArray(new String[arr.size()]);
                    //
                    //Enter your Email Id and password here
                    String fromemail="enter your email id here";
                    String fromemailpassword="enter its password";
                    String subject="GENTLE REMINDER: You are invited to attend Part One: Middleware & Backend on "+date1+" at "+timing1+".";
                    String emailmessage="Hello! Please attend this meeting scheduled on google meet using this link: ";
                    emailmessage+="https://meet.google.com/qza-juco-ofw"+"\n";
                    emailmessage+="Date of the meeting: "+date1+"\n";
                    emailmessage+="Timing of the meeting: "+timing1+"\n";
                    emailmessage+="Details of the meeting: "+agenda1+"\n";

                    Properties properties=new Properties();
                    properties.put("mail.smtp.auth","true");
                    properties.put("mail.smtp.starttls.enable","true");
                    properties.put("mail.smtp.host","smtp.gmail.com");
                    properties.put("mail.smtp.port","587");

                    Session session=Session.getDefaultInstance(properties,new javax.mail.Authenticator(){
                        @Override
                        protected PasswordAuthentication getPasswordAuthentication(){
                            return new PasswordAuthentication(fromemail,fromemailpassword);
                        }
                    });

                    try{
                        MimeMessage message=new MimeMessage(session);
                        message.setFrom(new InternetAddress(fromemail));
                        for(String i: a){
                            message.addRecipient(Message.RecipientType.TO, new InternetAddress(i));
                        }
                        message.setSubject(subject);
                        message.setText(emailmessage);
                        Transport.send(message);
                    }catch(Exception e){
                        error=1;
                        System.out.println(""+e);
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
                else{
                    //Enter your Email Id and password here
                    String fromemail="enter your email id here";
                    String fromemailpassword="enter its password";
                    String subject="GENTLE REMINDER: You are invited to attend Part One: Middleware & Backend on "+date1+" at "+timing1+".";
                    String emailmessage="Hello! Please attend this meeting scheduled on google meet using this link: ";
                    emailmessage+="https://meet.google.com/qza-juco-ofw"+"\n";
                    emailmessage+="Date of the meeting: "+date1+"\n";
                    emailmessage+="Timing of the meeting: "+timing1+"\n";
                    emailmessage+="Details of the meeting: "+agenda1+"\n";

                    Properties properties=new Properties();
                    properties.put("mail.smtp.auth","true");
                    properties.put("mail.smtp.starttls.enable","true");
                    properties.put("mail.smtp.host","smtp.gmail.com");
                    properties.put("mail.smtp.port","587");

                    Session session=Session.getDefaultInstance(properties,new javax.mail.Authenticator(){
                        @Override
                        protected PasswordAuthentication getPasswordAuthentication(){
                            return new PasswordAuthentication(fromemail,fromemailpassword);
                        }
                    });

                    try{
                        MimeMessage message=new MimeMessage(session);
                        message.setFrom(new InternetAddress(fromemail));
                        for(int i=0;i<toemail.length;i++){
                            message.addRecipient(Message.RecipientType.TO, new InternetAddress(toemail[i]));
                        }
                        message.setSubject(subject);
                        message.setText(emailmessage);
                        Transport.send(message);
                    }catch(Exception e){
                        error=1;
                        System.out.println(""+e);
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
                if(error==0){
                    String query="insert into meeting(date,timing,agenda) values(?,?,?)";
                    PreparedStatement st1 =con.prepareStatement(query);
                    st1.setString(1,date1);
                    st1.setString(2,timing1);
                    st1.setString(3,agenda1);
                    int count = st1.executeUpdate();
                    if(count>0)
                    {JOptionPane.showMessageDialog(null,"Meeting set up!");}
                    date.setText("");
                    agenda.setText("");
                    timing.setText("");
                    emails.setText("");
                    String query1="select * from meeting";
                    PreparedStatement st2=con.prepareStatement(query1);
                    ResultSet rs2=st2.executeQuery();
                    t01.setModel(DbUtils.resultSetToTableModel(rs2));
                }
                con.close();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void allstudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allstudentsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"You have selected to setup meeting for all students.");
    }//GEN-LAST:event_allstudentsActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea agenda;
    private javax.swing.JCheckBox allstudents;
    private javax.swing.JTextField date;
    private javax.swing.JLabel datevar;
    private javax.swing.JTextArea emails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable t01;
    private javax.swing.JLabel timevar;
    private javax.swing.JTextField timing;
    // End of variables declaration//GEN-END:variables
}
